version: '3.8'
services:
  bus-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: bus-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /home/shreemateshwaribus/sql-lite-db/bus_payments.db:/app/backend/app/bus_payments.db

  passenger-webapp:
    build:
      context: .
      dockerfile: passenger-webapp/Dockerfile
    container_name: passenger-webapp
    restart: unless-stopped
    ports:
      - "3002:80"
    depends_on:
      - bus-backend

